version: "3.8"
services:
  database:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: whos-that-pokemon
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
